# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - 'master'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repository: 'drtools/alpine-conda'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
      displayName: Set the tag name as an environment variable
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/alpine-conda/Dockerfile'
        repository: $(repository)
        containerRegistry: dockerhubServiceConnection
        tags: |
          $(VERSION_TAG)
          latest
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhubServiceConnection
    - task: Docker@2
      displayName: Push the image
      inputs:
        command: push
        repository: $(repository)
        containerRegistry: dockerhubServiceConnection
        tags: |
          $(VERSION_TAG)
          latest
