# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/alpine-conda/Dockerfile'
        repository: drtools/alpine-docker
        containerRegistry: dockerhubServiceConnection
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhubServiceConnection
    - task: Docker@2
      displayName: Push the image
      inputs:
        command: push
        repository: drtools/alpine-docker
        containerRegistry: dockerhubServiceConnection
        tags: |
          $(tag)